{% set name = "google-cloud-monitoring-dashboards" %}
{% set version = "2.7.1" %}
{% set sha256 = "4aee3e03539e1f6a468d0a25fa7cd4a47ee89c1c0f9ad4121baace650a66434e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-api-core-grpc >=1.26.0,<2.0.0dev
    - proto-plus >=0.4.0
    - packaging >=14.3

test:
  imports:
    - grpc
    - google.cloud.monitoring_dashboard
    - google.cloud.monitoring_dashboard.v1

about:
  home: https://github.com/googleapis/python-monitoring-dashboards
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Monitoring Dashboards API client library
  description: "Monitoring Dashboards API is a Google Cloud service that lets client applications manage dashboard configurations used in the Stackdriver UI.\nSee the [quick start guide](https://googleapis.dev/python/monitoring-dashboards/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/monitoring-dashboards/latest/index.html
  dev_url: https://github.com/googleapis/python-monitoring-dashboards

extra:
  recipe-maintainers:
    - parthea
